version: '3.8'

services:
  minio:
    container_name: stickermap-minio
    image: 'bitnami/minio:2025.2.28'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=streetart
    volumes:
      - minio:/bitnami/minio/data

  postgres:
    container_name: stickermap-postgres
    image: bitnami/postgresql:17.4.0
    environment:
      POSTGRESQL_DATABASE: stickermap
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db:/bitnami/postgresql

volumes:
  db:
  minio: